title: mjeanroy.dev
author: Mickael Jeanroy
description: mjeanroy.dev website
url: https://mjeanroy.dev
email: mickael.jeanroy@gmail.com
baseurl: /
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

twitter:
  username: mickaeljeanroy

compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []
