title: Mickael Jeanroy Website
author: Mickael Jeanroy
description: Welcome to mickael jeanroy's website
url: https://mjeanroy.dev
email: mickael.jeanroy@gmail.com
baseurl: /
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

ga:
  id: UA-163949403-1

twitter:
  username: mickaeljeanroy

plugins:
  - jekyll-feed

compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []
