title: mjeanroy.dev
author: Mickael Jeanroy
description: mjeanroy.dev website
url: https://mjeanroy.dev
baseurl: /
markdown: kramdown

sass:
    sass_dir: _sass
    style: compressed

twitter:
    username: mickaeljeanroy
